### ISSUE TITLE
Manage TrustAnchor Firmware

### ISSUE THREAD

**Issue by eckelj** [rddl-network/trusted-anchor-firmware#8]
- [ ] Create release via tagging
- [ ] build the firmware (only ESP32C3) via GH actions
- [ ] deploy the firmware to the ta_Attest service
- [ ] add a new download link to the ta_attest service: /ta_firmware:
- [ ]    patch firmware with random identity
- [ ]    compute checksum and patch the value
- [ ]    register random key to planetmint
